export enum DriverContractStatuses {
    Active = 0,
    Suspended = 1,
    Inactive = 2
}

// export function getEnumValues(enumObj: any): { key: string, value: number }[] {
//   return Object.keys(enumObj)
//     .filter(key => isNaN(Number(key))) // Filter out the numeric keys generated by TypeScript
//     .map(key => ({ key, value: enumObj[key] }));
// }

